name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: windows-latest
    env:
      MONGOMS_VERSION: 7.0.14
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - run: npm ci
      - run: npm run build
      - run: npm test
